### ISSUE TITLE
いい感じのOGImage欲しいな

### ISSUE THREAD

**Issue by at946** [at946/tenkiru#197]
AIさんに書いていただいたような。

**Comment by gennei** [comment]
[Adobe Firefly – 誰でも使える生成AI](https://www.adobe.com/jp/sensei/generative-ai/firefly.html)

このあいだブログ記事のイメージはこれで書いてもらいました。

**Comment by gennei** [comment]
DALL-E3 に描いてもらった。なんか違うよなあ。

<img width="827" alt="スクリーンショット 2023-11-07 23 32 08" src="https://github.com/at946/tenkir/assets/6353363/06d59cc9-2e63-4d68-965c-3289106d59d4">
